### ISSUE TITLE
Use MariaDB's LGPL c++ connector to avoid GPL

### ISSUE THREAD

**Issue by fire** [rbock/sqlpp11-connector-mysql#1]
Would it be possible to use https://mariadb.com/products/connectors-plugins to avoid GPL? It says it's api compatible with the mysql connector.

**Comment by fire** [comment]
It appears to be just a switch on https://github.com/rbock/sqlpp11-connector-mysql/blob/master/tests/CMakeLists.txt#L5 to the different library.

**Comment by rbock** [comment]
Yes, that should be possible. I am not sure how best to handle it. Maybe it makes sense to create a new repository? Or via a flag for cmake?
