### ISSUE TITLE
best practice for managing db connection?

### ISSUE THREAD

**Issue by JamesXiao** [rbock/sqlpp11-connector-mysql#11]
Dear:
The sample code on the project page shows a way to init a db connection

```
    auto config = std::make_shared<mysql::connection_config>();
    config->user = "root";
    config->database = "sqlpp_mysql";
    config->debug = true;
    mysql::connection db(config);
```

I am wondering if this is the standard way of calling this lib in real projects? 
How can I address the issue of database connection pool for better resource reusing while using the sqlpp11-mysql-connector?

**Comment by rbock** [comment]
Dear James,

As of now, you have to write the connection pool yourself. I haven't gotten to it yet. I think I would store the connections as unique_ptr and move those out of and back into the pool via RAII.

Contributions welcome, of course :-)

Best,

Roland

**Comment by iriselia** [comment]
Hi James,

Roland, Erroneous1, and I have been working on an experimental connection_pool recently. There is currently no documentation for it but it has been pushed to the master branch. [https://github.com/rbock/sqlpp11/pull/155](https://github.com/rbock/sqlpp11/pull/155)
