### ISSUE TITLE
CMAKE 3.4.3 GIVES WARNING: POLICY CMP0054 NOT SET

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11-connector-mysql#14]
When I run CMake 3.4.3 on the CMakeLists.txt file for this project I get the following warning and I am not sure if I should set policy CMP0054 or leave it unset...

Regards,
Juan

Warning is as follows:

CMake Warning (dev) at CMakeLists.txt:32 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by rbock** [comment]
I assume this is about the CMakeLists.txt in sqlpp11?

Does the warning go away if you replace

```
if (NOT MSVC)
```

with 

```
if (NOT DEFINED MSVC)
```

?

**Comment by juandent** [comment]
Hi,
No, it is in the CMakeList.txt in sqlpp11-connector-mysql-master and it does not contain MSVC anywhere...
