### ISSUE TITLE
Changes made --- yet not able to push changes

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11-connector-mysql#16]
Hi Roland,

Got a new laptop and installed everything. Changes have been made to this project and have commited them in GitHub Desktop for Windows, yet when I choose Pull Request to join with Master, it tells me I don't have permission.

My branch is called "make-it-work-with-MSVC".

This is my first experience wiuth using GitHub for "group development" so please give me a small push here so I can share the changes...

Regards,
Juan Dent

**Comment by rbock** [comment]
Hi Juan,

The normal procedure is for you to fork the repository you want to contribute to, make your changes and then to create a pull request. See for instance: https://help.github.com/articles/using-pull-requests/

Best,

Roland

PS: Looking forward to seeing your changes.
PPS: Please try not to "hijack" other threads. I am going to remove your messages from the sybase thread as they are not related.

**Comment by juandent** [comment]
Sorry for "hijacking" 
Thanks for the link - will look into it✌🏽️
Juan
