### ISSUE TITLE
How to obtain libraries mysqlclient and mysqlclient_r on UBUNTU 16.04?

### ISSUE THREAD

**Issue by lgong30** [rbock/sqlpp11-connector-mysql#23]
While building sqlpp11-connector-mysql, I found the libraries mysqlclient and mysqlclient_r were missing on my ubuntu 16.04. 
I am wondering which package should I install to obtain these two libraries.

Why do not use mariadb client  instead of mysqlclient (just as what you did under MSVC)?

**Comment by rbock** [comment]
Hi,

You could just use mariadb. On the systems that I know that use mariadb, there are libmysql* symbolic links. If those are not present on your system, maybe you could extend the `FindMySql.cmake` file and create a pull request? That would be great!

As for the Windows part: For quite some time I could not get libmysql to link with anything I built on appveyor. I was experimenting with mariadb and had compilation problems. I reported a few bugs and gave up. Some of this seems to be fixed now as the appveyor builds complete successfully but it is certainly not in a very good state.

**Comment by lgong30** [comment]
I have tried, everything went well except for the second test, i.e., SampleTest. The
second test failed while reallocating buffer, the following gives the detail:

2: MySQL debug: Preparing: 'SELECT tab_sample.alpha,tab_sample.beta,tab_sample.gamma FROM tab_sample WHERE (((tab_sample.alpha<>?) AND (tab_sample.beta<>?)) AND (tab_sample.gamma<>?))'
2: MySQL debug: Constructing prepared_statement, using handle at 0x20628d0
2: MySQL debug: binding integral parameter 7 at index: 0, being not null
2: MySQL debug: binding text parameter wurzelbrunft at index: 1, being not null
2: MySQL debug: binding boolean parameter true at index: 2, being not null
2: MySQL debug: Executing prepared_statement
2: MySQL debug: Constructing bind result, using handle at 0x20628d0
2: MySQL debug: binding integral result 0 at index: 0
2: MySQL debug: binding text result at index: 1
2: MySQL debug: binding boolean result 
2:  at index: 2
2: MySQL debug: Binding results for handle at 0x20628d0
2: MySQL debug: Accessing next row of handle at 0x20628d0
2: MySQL debug: Need to reallocate buffer at index 1 for handle at 0x20628d0
2: Exception: MySQL: Fetch column after reallocate failed: 
2/6 Test #2: SampleTest .......................***Failed    0.23 sec

It seems that this exception is thrown by `bool bind_result_t::next_impl()` in [bind_result.cpp](https://github.com/rbock/sqlpp11-connector-mysql/blob/master/src/bind_result.cpp#L271).

Do you have any hint for me to solve it?


Thanks!
-- Long

**Comment by rbock** [comment]
Hmm, that looks strange.

Can you try to dig deeper into the problem by printing `r.bound_len`, `param.buffer_length` and the actual return value of `mysql_stmt_fetch_column`?

Thanks,

Roland

**Comment by lgong30** [comment]
After a deeper dig, I got the following mysql error code:

> Error: 2051 (CR_NO_DATA)
> Message: Attempt to read column without prior row fetch

Original exception output is:

`Exception: MySQL: Fetch column after reallocate failed: 2051`

To get the above output, I changed `mysql_stmt_error` to `mysql_stmt_errno` in [bind_result.cpp](https://github.com/rbock/sqlpp11-connector-mysql/blob/master/src/bind_result.cpp#L272), since 
I got nothing (empty string) from   `mysql_stmt_error`.

Thanks!
- Long

**Comment by rbock** [comment]
Please try again with the new version on develop. It does not change anything functionally but prints a few more messages.

Which library are you using? mysql or mariadb, which version?

**Comment by lgong30** [comment]
My mysql server version is: `mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapper`
For the connector, I used [mariadb client (3.0.2)](https://github.com/MariaDB/mariadb-connector-c) instead of mysqlclient. 

The following is exception thrown when running `ctest` on the new version on develop.

> 2: Exception: MySQL: Fetch column after reallocate failed: error-code: 1, stmt-error: , stmt-errno: 2051

**Comment by rbock** [comment]
Thanks. I'll need some time to setup mariadb.

**Comment by rbock** [comment]
See https://github.com/rbock/sqlpp11-connector-mysql/issues/39 (it is a maria db client bug it seems).

Closing this one.
