### ISSUE TITLE
Which supported datatype is best for handling money amounts?

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11-connector-mysql#28]
Hi Roland,
As I am starting a small project to begin use of your library, I found decimal and numeric are not allowed data types (but they are the only that allow exact 2 decimal places for money amounts). I guess one could use double, but that is not exact.

I would like to know what you suggest.
Thanks!
Juan

**Comment by rbock** [comment]
Hi Juan,

I would use bigint or some other integral type and combine it with information about the currency. Not all currencies have a minor unit that represents 1/100th of the main unit.

Best,

Roland

**Comment by juandent** [comment]
Hi Roland 

Just to make sure I get that correctly :
all amounts would be multiplied by 100 for storage purposes 

I know of a small library that deals with such representation so all would be well!!

Thanks again!

**Comment by rbock** [comment]
Hi Juan,

That sounds good to me.

Best,

Roland
