### ISSUE TITLE
Prepared Statement Select does not call mysql_free_result

### ISSUE THREAD

**Issue by lucianodasilva** [rbock/sqlpp11-connector-mysql#35]
I have a couple of long living prepared statements. When i call a select prepared statement, its results apparently never call mysql_free_result, which causes other statements to fail with "Command out of sync" exceptions, even though the result instance has fallen out of scope.

Update and insert prepared statements do not seem to have issues. Could this be a bug or am i missing a mechanism to force a select prepared statement to release its mysql results?

**Comment by rbock** [comment]
That sounds like a bug. I'll look into it.

**Comment by rbock** [comment]
You could help a lot by creating a small unit test that currently fails.

**Comment by lucianodasilva** [comment]
I didn't have the opportunity to create the unit test, i'm going to have a go at it as soon as i can. I've tried to track down the possible issue this morning and found that a possible solution would be to add a "mysql_stmt_free_result" to bind_result_t's destructor. As far as i can tell it seemed to be an appropriate approach, but i am not confident enough to trust it.

**Comment by rbock** [comment]
Thanks for the info. That sounds quite reasonable. I probably won't be able to look into it in much detail tomorrow, but should find the time on the weekend.

**Comment by rbock** [comment]
Hi,

I am at a bit of a loss trying to reproduce the problem. I tried adding a second query execution to `test/Select.cpp`, which worked just fine.

I added `mysql_stmt_free_result` to `bind_result_t`'s destructor nonetheless. I don't think it hurts, but as said, I can't tell if it helps.

Please give it a try, I pushed the changes to develop.

Cheers,

Roland

**Comment by lucianodasilva** [comment]
Hi Roland. I've added a small test able to replicate the issue and made a pull request. I'm terribly sorry for the delay. The issue seems to be fixed with your latest changes.

Thank you very much for your time.

Regards,
Luciano.

**Comment by rbock** [comment]
Hi Luciano,

Thanks for reporting the issue and the test to confirm it.

Cheers,

Roland

**Comment by lucianodasilva** [comment]
Hi Roland, just one small question. Do you have a ballpark idea on when could this change make it to a release?

**Comment by rbock** [comment]
Done, thanks for pinging :-)
