### ISSUE TITLE
Unable to compile with mysql connector/c 8.0

### ISSUE THREAD

**Issue by RavenX8** [rbock/sqlpp11-connector-mysql#37]
OS: windows
Arch: x64
Compiler: VS2017 Community Update 5
Connector: Mysql 8.0 Connector/C (installed with mysql server 8)
Standard: C++-17

In 8.0 they removed `my_bool` and replaced it with the normal `bool` type. This causes the library to fail comp.

https://dev.mysql.com/doc/refman/8.0/en/c-api-prepared-statement-data-structures.html

**Comment by RavenX8** [comment]
Looks like this should be fixed by 71120340682fe4b995f6220f5e0f8ef9834176e3.

I'll test when I get home.

**Comment by rbock** [comment]
I consider this fixed for now.
