### ISSUE TITLE
Not being able to compile

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11-connector-mysql#4]
I downloaded this project and ran:

cmake CMakeLists.txt
make

and get this error:

Scanning dependencies of target sqlpp-mysql
[  6%] Building CXX object src/CMakeFiles/sqlpp-mysql.dir/connection.cpp.o
In file included from /Users/juandent/Programs/C++/sqlpp11-connector-mysql-master/src/connection.cpp:30:
/Users/juandent/Programs/C++/sqlpp11-connector-mysql-master/src/detail/prepared_statement_handle.h:31:10: fatal error: 'mysql/mysql.h' file not
      found
# include <mysql/mysql.h>

```
     ^
```
## 1 error generated.

Any help will be greatly appreciated!!

Juan

**Comment by rbock** [comment]
Hi,

sounds like you do not have libmysqlclient installed. Depending on your system it would be a package like 'libmysqlclient-dev`.

Hope that helps pointing you in the right direction.

General remark: You might want to give more details about the OS and compiler you are using when reporting errors. It makes things easier for those who you are asking for help :-)

Best,

Roland

**Comment by juandent** [comment]
Hi and thanks...
I am using OS X (10.11.3) and I do have libmysqlclient installed (actually there are several libraries in the following path:

/usr/local/mysql-connector-c-6.1.6-osx10.8-x86_64/lib

The files there are:

libmysqlclient_r.18.dylib
libmysqlclient_r.a
libmysqlclient_r.dylib
libmysqlclient.18.dylib
libmysqlclient.a
libmysqlclient.dylib

the include path is at 

/usr/local/mysql-connector-c-6.1.6-osx10.8-x86_64/include

but that include directory has a subdirectory called mysql but NO mysql.h inside that subdirectory, so I don't see how it could find a <mysql/mysql.h>

Also, do I need to set environment include variables?

the compiler used is Xcode 7.2 clang

Please one last push, maybe I a m close now... Did I install the C connector libraries in the wrong dir?

Thanks
Juan

**Comment by juandent** [comment]
One last thing to point out: in the include folder for the C connector for MySql or the include folder  for the MySql server installation, there is NO mysql.h file inside a mysql folder ANYWHERE... Thus how can it find <mysql/mysql.h>? It does not exist....

**Comment by juandent** [comment]
The only mysql/mysql.h I can find is in:

/Users/juandent/Programs/C++/sqlpp11-connector-mysql-master/include/sqlpp11/mysql/mysql.h

but none in the client connectivity in /usr/local/.......

**Comment by rbock** [comment]
I am not an expert for OSX installation, but a bit of googling tells me that you need to install mysql with some option to install the header files as well.

**Comment by juandent** [comment]
I apologise for taking some of your time .. but in installing the client libraries via the C connector from MySQL, I have the include folder with what seems all the .h files for connecting to a C program. So it would seem that I have the header files...

**Comment by rbock** [comment]
No problem. Glad you found it.

BTW: There might be a problem with running the tests. A colleague of mine pointed out that MySQL 5.7 and beyond are not happy with the create table commands. Those should be simple to fix, I just haven't gotten around to do that.

Closing this issue now.
