### ISSUE TITLE
Microseconds ignored when selecting datetime column

### ISSUE THREAD

**Issue by akirashimosoeda** [rbock/sqlpp11-connector-mysql#47]
The code only takes into account down to milliseconds IF the fourth fractional second character is '\0'. Microseconds is not evaluated (I guess it should evaluate that seventh character is '\0').

**Comment by rbock** [comment]
Thanks for the hint. Looking closer at it, the code would fail in multiple situations, e.g. when precision is only two digits...

Pushed a better (IMO) version to develop. Please check it out.
