### ISSUE TITLE
Crash of queries due to MYSQL_RES that is NULL

### ISSUE THREAD

**Issue by LouisDuVerdier** [rbock/sqlpp11-connector-mysql#49]
Hello,

We encountered a crash in very special conditions that are hard to reproduce (we did not understand all the issue yet), leading to a NULL MYSQL_RES* and a crash when entering mysql_fetch_row with a NULL pointer, when doing a SELECT statement.

We found that the origin of the crash is the following:

```
    char_result_t connection::select_impl(const std::string& statement)
    {
      execute_statement(*_handle, statement);
      std::unique_ptr<detail::result_handle> result_handle(
          new detail::result_handle(mysql_store_result(_handle->mysql.get()), _handle->config->debug));
      if (!result_handle)
      {
        throw sqlpp::exception("MySQL error: Could not store result set: " +
                               std::string(mysql_error(_handle->mysql.get())));
      }

      return {std::move(result_handle)};
}
```

Given the following implementation of result_handle that contains an `operator!()`, the check `if (!result_handle)` should most likely be written `if (!*result_handle)` instead, because otherwise the operator!() used is the one of unique_ptr (with a check if the ptr is null - that does not make sense because the ptr is new-ed right above) instead of the one of result_handle that checks if MYSQL_RES is null.

Do you think this fix could be integrated?

Thank you,
Best regards,
Louis

**Comment by rbock** [comment]
Nice find! Yes, a pull request would be welcome :-)

**Comment by LouisDuVerdier** [comment]
Hello,

We could confirm that the fix (adding the missing star) fixes the issue and correctly prints the error. It was a timeout - "Could not store result set: Lock wait timeout exceeded; try restarting transaction" - due to a big query, and it segfaults on the next SELECT without the fix instead of printing the error).

Please don't hesitate to fix it directly if you can, I cannot pull the repository for proxy reasons at work, sorry about that.

Best regards,
Louis

**Comment by rbock** [comment]
OK, pushed to develop.

**Comment by LouisDuVerdier** [comment]
Thank you!

**Comment by LouisDuVerdier** [comment]
Hello,

I can see the same issue in char_result.h, line 67, where the issue is similar but for the method next():

```
      template <typename ResultRow>
      void next(ResultRow& result_row)
      {
        if (!_handle) <--- issue here
        {
          result_row._invalidate();
          return;
        }
```

There is here a missing star as well. When grep-ing "if (!_handle)" I can see that there are other uses, so maybe there is something to do as well there.

Could you please integrate a fix as well?

Thank you,
Best regards,
Louis

**Comment by rbock** [comment]
Thanks!
I just pushed a new commit on develop.

**Comment by LouisDuVerdier** [comment]
Thank you!
