### ISSUE TITLE
Xcode 7.2 does not support thread_local => no way to build the MySQL connector for sqlpp11

### ISSUE THREAD

**Issue by juandent** [rbock/sqlpp11-connector-mysql#5]
Hi,

After much searching around, I have been stopped by the frustrating reality that Xcode 7.2 does not yet support thread_local variables and thus it is currently impossible to build "sqlpp11-connector-mysql-master".  Connection.cpp uses this like so:

void execute_statement(detail::connection_handle_t& handle, const std::string& statement)
      {
        thread_local MySqlThreadInitializer threadInitializer;

```
    if (handle.config->debug)
      std::cerr << "MySQL debug: Executing: '" << statement << "'" << std::endl;

    if (mysql_query(handle.mysql.get(), statement.c_str()))
    {
      throw sqlpp::exception("MySQL error: Could not execute MySQL-statement: " +
                             std::string(mysql_error(handle.mysql.get())) + " (statement was >>" + statement +
                             "<<\n");
    }
  }
```

If someone knows a workaround, I would be deeply grateful! Such a shame for a great library...'

Thanks again,
Juan

**Comment by rbock** [comment]
Hi Juan,

I currently can't test with Xcode directly, but I will setup testing on travis.ci soon.

For the time being, please try to use boost.thread:

```
static boost::thread_specific_ptr<MySqlThreadInitializer> mysqlThreadInit;
if (!mysqlThreadInit.get()
{
     mysqlThreadInit.reset(new MysqlThreadInit);
}
```

Best,

Roland

**Comment by juandent** [comment]
Hi Roland!

Your idea worked!! Thank you so much!!

Juan

**Comment by rbock** [comment]
Glad it worked out :-)

**Comment by CapSel** [comment]
This solution is really bad.
C++ from Apple does not support thread_local but the "original" clang/libc++ support it. This is very old BUG or FEATURE of Apple's XCode environment - not clang/llvm/libc++.

**Comment by rbock** [comment]
So what would be a good solution?

**Comment by CapSel** [comment]
The "best" solution is for Apple to fix this issue.
Simplest solution is to test for `__APPLE__`.

**Comment by CapSel** [comment]
CMake solution: https://cmake.org/cmake/help/v3.0/variable/APPLE.html

**Comment by rbock** [comment]
Since I don't think I have that kind of pull at Apple, I like the `__APPLE__` version best.

Care to write a pull request?

**Comment by CapSel** [comment]
#29 
How can I fix issue from AppVeyor?
