### ISSUE TITLE
mysql replace into command 

### ISSUE THREAD

**Issue by kevinmgyu** [rbock/sqlpp11-connector-mysql#50]
how to implement replace into command ,could you give some information ,thanks

**Comment by rbock** [comment]
Basically there are two options:

 - you can use custom_query, see sqlpp11/tests/CustomQuery.cpp for examples
 - you can write clauses for that, see for instance sqlpp11-connector-sqlite3/include/sqlpp11/sqlite3/insert_or.h

**Comment by kevinmgyu** [comment]
I got it, thanks again

**Comment by kevinmgyu** [comment]
how to implement batch replace command , and I only see the batch insert from wiki.

**Comment by rbock** [comment]
There is no ready-to-use library function for it, I am afraid. Thus, the answer is the same two options, although it certainly will be a bit harder.

**Comment by kevinmgyu** [comment]
thanks your reply
