### ISSUE TITLE
database name not used

### ISSUE THREAD

**Issue by frits-greuter** [rbock/sqlpp11-connector-mysql#53]
I downloaded today and it did not work out of the box.
 I got the sql error: can not select db ' '

2. I needed to modify the code in connection_handle.cpp from:
        if (!mysql_real_connect(mysql.get(), config->host.empty() ? nullptr : config->host.c_str(),
                                config->user.empty() ? nullptr : config->user.c_str(),
                                config->password.empty() ? nullptr : config->password.c_str(), 
                                nullptr , config->port,
                                config->unix_socket.empty() ? nullptr : config->unix_socket.c_str(),
                                config->client_flag))

to:
        if (!mysql_real_connect(mysql.get(), config->host.empty() ? nullptr : config->host.c_str(),
                                config->user.empty() ? nullptr : config->user.c_str(),
                                config->password.empty() ? nullptr : config->password.c_str(), 
				config->database.empty() ? nullptr : config->database.c_str(), 
				config->port,
                                config->unix_socket.empty() ? nullptr : config->unix_socket.c_str(),
                                config->client_flag))

Why is the config->database variable not used?

Platform: windows.

**Comment by rbock** [comment]
Hi,

database and charset are set here:

https://github.com/rbock/sqlpp11-connector-mysql/blob/5e0913c843e0cf7ede439f05373033ceb2f39d11/src/connection.cpp#L154

Can you post a complete example of what failed?

Thanks,

Roland

**Comment by frits-greuter** [comment]
Apologies: it does not reproduce anymore.
