### ISSUE TITLE
ddl2cpp issues

### ISSUE THREAD

**Issue by digitalist** [rbock/sqlpp11-connector-mysql#6]
1) does not work with default mysql's show create table because of '`' around table/column names
2) does not recognize 'timestamp' column type

**Comment by rbock** [comment]
Good point regarding the forward ticks used by mysql. I'll try to fix that, soon.

Regarding the timestamp: I left it out til now. Mapping it to sqlpp::time_point is a bit hairy since time_point is agnostic of time zones. I might issue a warning in the script.

What do you think?

**Comment by digitalist** [comment]
a warning is  good idea.
Timestamps are in heavy usage in mysql world, but you're right about timezones. It's a little tricky, but I hope changes needed (getting timezone from os etc. will touch only connector code)

**Comment by rbock** [comment]
Please take a look at the script update I just pushed on sqlpp11 develop.

Personally, I am not using timestamps and if I were, I wouldn't dream of using any other timezone than UTC. I honestly do not know if timezones in timestamps actually present a real problem or just a theoretical one. If you think that is a real problem, please open a separate issue.

**Comment by digitalist** [comment]
I didn't try to compile resulting header for now, but it generates a header file. Thanks.
testfile was

```
CREATE TABLE `history` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `command` text,
  `arguments` text,
  `cwd` text,
  `created` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `tag` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=53319 DEFAULT CHARSET=latin1
```

**Comment by digitalist** [comment]
I mean, it's a progress, update master, please

**Comment by rbock** [comment]
Done :-)

**Comment by digitalist** [comment]
tested, it works! it... SELECTS!
