### ISSUE TITLE
How to create mysql::connection without config

### ISSUE THREAD

**Issue by maituduy** [rbock/sqlpp11-connector-mysql#60]
I try to create class contain mysql::connection object:
>class Database {
>  
>  Database(std::shared_ptr<mysql::connection_config> config) {
>    // set config code ???   
>  }
>
>  private:
>    mysql::connection db;
>}

but i the error "error: no matching function for call to ‘sqlpp::mysql::connection::connection()’" at "mysql::connection db" line.
 
How do I initialize my `db` variable in Database constructor?
Thanks!

**Comment by rbock** [comment]
Have you looked a the tests? They connect to a database.

In your case: You need to pass the parameter to the database constructor before the opening curly brace, i.e. something like:

```C++
class Database
{
    Database(std::shared_ptr<mysql::connection_config> config) 
     : db(config) 
    {
    // set config code ???
    }

    private:
    mysql::connection db;
};
```

**Comment by maituduy** [comment]
Thanks a lot!
