### ISSUE TITLE
Does sqlpp11 support a connection pool? What do I need to do?

### ISSUE THREAD

**Issue by AkideLiu** [rbock/sqlpp11-connector-mysql#62]
Does sqlpp11 support a connection pool with mysql? What do I need to do with mysql?

**Comment by AkideLiu** [comment]
For example, the code for database operation used sqlpp11 attached in following links : 

https://github.com/UAws/OOP-Project/blob/master/src/dao/SubjectDao.cpp

Currently i need to create db connection everytimes in each functions. It's really reduced performance. 

I would wandering that does sqlpp11 support connection pool or is there any better way to improve the performance of db connection? 

Thanks!

**Comment by rbock** [comment]
Hi,

The library does not provide a connection pool itself. I have never gotten around to writing one myself.

But of course, you could store connections in a pool.

Frank Park started to write a generic pool in sqlpp11 (see https://github.com/rbock/sqlpp11/blob/develop/include/sqlpp11/connection_pool.h). It is unfinished, but maybe you can use it as basis?

I'd be happy to accept pull requests to finish hat implementation.

Thanks,

Roland
