### ISSUE TITLE
How to return mysql auto incorrect when inserting a record in the table?

### ISSUE THREAD

**Issue by GCarneiroA** [rbock/sqlpp11-connector-mysql#67]
Dear, to return the field of auto increment of my table, currently I need to make a select with the data that were inserted to search for this information.

Somehow, it would be possible, when making an insertion, to return the line added in the database so that I can retrieve data such as auto increment fields and fields updated by internal triggers.

In my case, I need to return ```id AUTO_INCREMENT and created_time DATETIME```

My actual code is:
```
int User::insertUser(const std::string &username, const std::string &password, const std::string &email)
{
    m_connection->insert(insert_into(m_userTable).set(
        m_userTable.username = username, m_userTable.password = password, m_userTable.email = email));
                
    const auto &row = m_connection->run(
        select(all_of(m_userTable)).from(m_userTable)
            .where(m_userTable.username == username and m_userTable.password == password and m_userTable.email == email)
    );
    return row.front().id;
}
```

**Comment by GCarneiroA** [comment]
My actual code is:
```int User::insertUser(const std::string &username, const std::string &password, const std::string &email)
            {
                m_connection->insert(insert_into(m_userTable).set(
                    m_userTable.username = username, m_userTable.password = password, m_userTable.email = email));
                
                const auto &row = m_connection->run(
                    select(all_of(m_userTable)).from(m_userTable)
                        .where(m_userTable.username == username and m_userTable.password == password and m_userTable.email == email)
                );
                return row.front().id;
            }```

**Comment by rbock** [comment]
Hi,

`insert_into` returns the id. So I would use that one for the subsequent `select`.

Other than that, I don't know of a way that MySQL can yield inserted data as part of the insert call? PostgreSQL has the `RETURNING` clause. But I don't think there is an equivalent for MySQL?

Best,

Roland

**Comment by GCarneiroA** [comment]
In MySQL I can use triggers to change data in tables during insert / update, for example, when inserting a new record the created_time field is filled with the current date and time.

```insert_into``` returns the auto increment fields id ? I will test this, thanks :)
