### ISSUE TITLE
how can I set mysql options

### ISSUE THREAD

**Issue by ZerQAQ** [rbock/sqlpp11-connector-mysql#68]
Hi,

this is what I want to do
```
mysql_options(mysql_conn->_handle->mysql.get(), MYSQL_OPT_CONNECT_TIMEOUT,  &m_iOverTime);
mysql_options(mysql_conn->_handle->mysql.get(), MYSQL_OPT_READ_TIMEOUT,  &m_iOverTime);  
mysql_options(mysql_conn->_handle->mysql.get(), MYSQL_OPT_WRITE_TIMEOUT, &m_iOverTime);  
```
but _handle is private in sqlpp::mysql::connection, I cant find any public function to do this.

**Comment by rbock** [comment]
Hi,

Right, this is currently not exposed, but you could add a function to do so. Can you create a pull request?
