### ISSUE TITLE
enum/set support

### ISSUE THREAD

**Issue by digitalist** [rbock/sqlpp11-connector-mysql#7]
./ddl2cpp  -no-timestamp-warning ~/temp/test_enum.ddl ~/temp/tbl test_enum
testfile:

```
CREATE TABLE test_enum_set (
  oid int(11) NOT NULL DEFAULT '0',
  set_test set('test1', 'test2') NOT NULL DEFAULT '',
  enum_test enum('Yes','No') DEFAULT 'No'

) ENGINE=InnoDB DEFAULT CHARSET=cp1251;
```

results in:

```
Traceback (most recent call last):
  File "./ddl2cpp", line 184, in <module>
    traitslist = [NAMESPACE + '::' + types[sqlColumnType]];
KeyError: 'enum' #or KeyError 'set'
```

http://dev.mysql.com/doc/refman/5.7/en/constraint-enum.html
http://www.postgresql.org/docs/9.1/static/datatype-enum.html

**Comment by rbock** [comment]
While I am a big fan of enum in C++, I agree with this: http://komlenic.com/244/8-reasons-why-mysqls-enum-data-type-is-evil/

Anyway: As far as I can tell, set and enum are basically strings. You could therefore simply map enum and set to text. Right?

**Comment by digitalist** [comment]
enum can be bad, but I've seen a lot of usage for it in a huge production systems (online ads, antifraud etc), and it's as good as a raw C pointer\* is bad. You have to control them and you can't ignore them (because someone uses them)

set and enum are almost like strings, but mysql (and, I suppose other rdbms) treat enums/sets like named bitmask  - you can do bit operations on them and sometimes it's really helpful.  

For the current time it's a good enough solution to treat enum/set as text, better - treat them like flags (or native c++ enums), but sooner ddl enums work with ddl2cpp script the better.

**Comment by digitalist** [comment]
(note) enums are much faster then text/varchar, they do a great deal of  help to constraint a value, but they can be a pain in the ass to alter.

**Comment by digitalist** [comment]
speaking of this article:
imagine: you have about ~100 databases (it's a long running business), they MUST be fast enough. Aslo you have issues with replication and foreign keys (which are pain in the ass too), and you have about ~300 database servers .
And you have your team. Human factor. Someone sends trash to a field value... bad. Daemons go segfault etc. Enum prevents this.
In the end  it's  a question of balance between human factor, database architecture, scale and programming guidelines, but it's all we have as always... so - enums are frequent in the wild. Someone has to tame them.

**Comment by rbock** [comment]
I won't argue against you using enum :-)

I added enum and set (mapping them to text for now). If you make heavy use of enums and would rather like to map them to C++ enums, I'd be grateful if you could add such a mapping. Take a look at the other datatypes in sqlpp11/data_types. They are not hard to implement. The hardest part (I guess) will be to link column to enum type and string to enum value. I guess you will have to put that into the column spec.

Let me know if you want to try and/or need help with that.

**Comment by digitalist** [comment]
thanks, I'll close this issue after some testing. (And in the future I'll try to add some datatypes myself before raising an issue)

**Comment by rbock** [comment]
Looking forward to those new datatypes!
