### ISSUE TITLE
Error reported while installing sqlpp11-mysql

### ISSUE THREAD

**Issue by mscg-ssxd** [rbock/sqlpp11-connector-mysql#70]
I kept reporting the following error when I installed sqlpp11-mysql again:
I m sure my date path and sqlpp11 path are correct

`-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - found
-- Found Threads: TRUE  
CMake Warning (dev) at /usr/local/share/cmake-3.21/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (MYSQL) does
  not match the name of the calling package (MySql).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  cmake/FindMySql.cmake:49 (find_package_handle_standard_args)
  CMakeLists.txt:36 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found MYSQL: /usr/lib/x86_64-linux-gnu/libmysqlclient.so  
-- Using /usr/bin/c++ (compiler id: GNU)
CMake Error at CMakeLists.txt:43 (message):
  Can't find file date/date.h

Can't find date/date.h in /home/mscg/project/sqlpp11-connector-mysql-master/sqlpp11-connector-mysql-master/../date/include 
Please either
  - git clone https://github.com/howardhinnant/date /home/mscg/project/sqlpp11-connector-mysql-master/sqlpp11-connector-mysql-master/../date/include
  - set DATE_INCLUDE_DIR to point to the dir containing date/date.h from the date library
  - e.g. download and unzip a current version from https://github.com/howardhinnant/date to ../date
  -      -DDATE_INCLUDE_DIR=../date/include}

CMake Error at CMakeLists.txt:58 (message):
  Can't find file sqlpp11/sqlpp11.h

Can't find sqlpp11/sqlpp11.h in /home/mscg/project/sqlpp11-connector-mysql-master/sqlpp11-connector-mysql-master/../sqlpp11/include 
Please either
  - git clone https://github.com/rbock/sqlpp11 /home/mscg/project/sqlpp11-connector-mysql-master/sqlpp11-connector-mysql-master/../sqlpp11/include
  - download and unzip a current version from https://github.com/rbock/sqlpp11 to /home/mscg/project/sqlpp11-connector-mysql-master/sqlpp11-connector-mysql-master/../sqlpp11/include
  - set SQLPP11_INCLUDE_DIR to point to the dir containing sqlpp11/sqlpp11.h

-- Configuring incomplete, errors occurred!
See also "/home/mscg/project/sqlpp11-connector-mysql-master/sqlpp11-connector-mysql-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/mscg/project/sqlpp11-connector-mysql-master/sqlpp11-connector-mysql-master/build/CMakeFiles/CMakeError.log".`

CMakeError.log file:

`Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/mscg/project/sqlpp11-connector-mysql-master/sqlpp11-connector-mysql-master/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_9eab5/fast && /usr/bin/make  -f CMakeFiles/cmTC_9eab5.dir/build.make CMakeFiles/cmTC_9eab5.dir/build
make[1]: Entering directory '/home/mscg/project/sqlpp11-connector-mysql-master/sqlpp11-connector-mysql-master/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_9eab5.dir/src.c.o
/usr/bin/cc -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_9eab5.dir/src.c.o -c /home/mscg/project/sqlpp11-connector-mysql-master/sqlpp11-connector-mysql-master/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_9eab5
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_9eab5.dir/link.txt --verbose=1
/usr/bin/cc -rdynamic CMakeFiles/cmTC_9eab5.dir/src.c.o -o cmTC_9eab5 
/usr/bin/ld: CMakeFiles/cmTC_9eab5.dir/src.c.o: in function `main':
src.c:(.text+0x2d): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text+0x39): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x45): undefined reference to `pthread_cancel'
/usr/bin/ld: src.c:(.text+0x56): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_9eab5.dir/build.make:99: cmTC_9eab5] Error 1
make[1]: Leaving directory '/home/mscg/project/sqlpp11-connector-mysql-master/sqlpp11-connector-mysql-master/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:127: cmTC_9eab5/fast] Error 2

Source file was:
#include <pthread.h>

static void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

`

**Comment by rbock** [comment]
I am not sure I can help you with that?

If cmake cannot find your files, they aren't where it expects them, but I cannot see your directory structure or how/where you called cmake?

Seeing that cmake has trouble finding mysel and pthread seems to indicate that there are some fundamental flaws in your setup?

Did you maybe copy the whole build directory from one machine to another? 

I think I would start by deleting the build directory, create a new one and start from scratch. It might be a caching issue of cmake.

**Comment by mscg-ssxd** [comment]
> 我不确定我能帮到你吗？
> 
> 如果 cmake 找不到您的文件，则它们不在它期望的位置，但是我看不到您的目录结构或您如何/在何处调用 cmake？
> 
> 看到 cmake 无法找到 mysel 和 pthread 似乎表明您的设置存在一些基本缺陷？
> 
> 您是否可能将整个构建目录从一台机器复制到另一台机器？
> 
> 我想我会首先删除构建目录，创建一个新目录并从头开始。这可能是cmake的缓存问题。

**Comment by mscg-ssxd** [comment]
> I am not sure I can help you with that?
> 
> If cmake cannot find your files, they aren't where it expects them, but I cannot see your directory structure or how/where you called cmake?
> 
> Seeing that cmake has trouble finding mysel and pthread seems to indicate that there are some fundamental flaws in your setup?
> 
> Did you maybe copy the whole build directory from one machine to another?
> 
> I think I would start by deleting the build directory, create a new one and start from scratch. It might be a caching issue of cmake.

![1](https://user-images.githubusercontent.com/52558920/123919950-0a99e600-d9b8-11eb-9dd5-fe9f7c8e826c.png)
![2](https://user-images.githubusercontent.com/52558920/123919954-0bcb1300-d9b8-11eb-898e-c4e5dd878155.png)
![3](https://user-images.githubusercontent.com/52558920/123919956-0c63a980-d9b8-11eb-905d-8766f7c01213.png)
![4](https://user-images.githubusercontent.com/52558920/123919959-0cfc4000-d9b8-11eb-84bd-ec73f3a90633.png)


Sorry, just accidentally click close

I tried to install MySQL on a different computer, but it still failed. The picture above is the specific details. Can you help me see if there is any problem.

**Comment by rbock** [comment]
I think you were close.

Try `cmake ../ -DSQLPP11_INCLUDE_DIR=/usr/local/include -DDATE_INCLUDE_DIR=/usr/local/include`

**Comment by mscg-ssxd** [comment]
> I think you were close.
> 
> Try `cmake ../ -DSQLPP11_INCLUDE_DIR=/usr/local/include -DDATE_INCLUDE_DIR=/usr/local/include`

Thank you very much for your guidance. This method has been compiled successfully!
