### ISSUE TITLE
Why is it necessary to pass database parameter when creating a connection?

### ISSUE THREAD

**Issue by zhengminlai** [rbock/sqlpp11-connector-mysql#73]
In  line 53-56 of file: https://github.com/rbock/sqlpp11-connector-mysql/blob/master/src/detail/connection_handle.cpp
We have:
```
if (mysql_select_db(mysql, config.database.c_str()))
{
      throw sqlpp::exception("MySQL error: can't select database '" + config.database + "'");
}
```
But I think in general, we do not need to set the database when simply creating a connection to the mysql server. Instead, we  should first connect to the server, then we type `use  database_name` to conduct queries. Therefore, I suggest to remove the codes mentioned above.

**Comment by rbock** [comment]
I see your point. But most users actually only need to connect to one database per connection, though. So how about

```
if (!config.database.empty() and mysql_select_db(mysql, config.database.c_str()))
{
      throw sqlpp::exception("MySQL error: can't select database '" + config.database + "'");
}
```

**Comment by zhengminlai** [comment]
That's better.

**Comment by rbock** [comment]
pushed to develop. Thanks!
