### ISSUE TITLE
emplace & move constructor

### ISSUE THREAD

**Issue by digitalist** [rbock/sqlpp11-connector-mysql#9]
maybe I'm missing something, but here's the question
I want to make a `map<config, connection>`, so I could manage different servers/users connections without making unneeded connections.
`map.emplace(config, std::move(sqlpp::mysql::connection(config)))` fails to compile saying (gcc 5.2):

`error: use of deleted function ‘sqlpp::mysql::connection::connection(const sqlpp::mysql::connection&)’`

How do I deal with this situation? Implement a move constructor?

**Comment by rbock** [comment]
Hi,

yes, as of now, the move constructor is explicitly deleted. That needs to be changed.

I've got a lot on my plate this week. Do you want to take a look into it? It is probably just replacing `=delete` with with `=default` for move constructor and move assignment.

Best,

Roland

**Comment by digitalist** [comment]
I'm trying %) will report later

**Comment by digitalist** [comment]
there's a pull-request. seems working. maybe I should add some tests for this case

**Comment by rbock** [comment]
A test case would be great, indeed :-) Thanks for your effort!

**Comment by rbock** [comment]
See pull request #10
